---
# 区服: start,stop,check,reload

- name: find game directory
  find:
    paths: "{{game_directory}}"
    file_type: directory
    use_regex: True
    patterns: 
      - "{{zone_name}}_*"
  register: zonedir

- name: "zone {{act}}"
  shell: |
    cd {{item.path}}
    sh game_opt.sh {{act}}
  with_items: "{{zonedir.files}}"
  when: "(item.path.split('_')[2]|int) in zone_num"
