---
- name: find game directory
  find:
    paths: "{{game_directory}}"
    file_type: directory
    use_regex: True
    patterns: 
      - "{{zone_name}}_*"
  register: zones

- name: "update binfile"
  copy: 
    src: "{{bin_file}}"
    dest: "{{item.path}}" 
    mode: "0755"
  register: copy_ret
  with_items: "{{zones.files}}"
  when: "(item.path.split('_')[2]|int) in zone_num and opt == 'bin'"

- name: "md5sum binfile"
  shell: |
    md5sum {{item.path}}/gameserv
  register: shell_ret
  with_items: "{{zones.files}}"
  when: "(item.path.split('_')[2]|int) in zone_num and opt == 'bin'"

- name: "update config"
  subversion: 
    repo: "{{svn_url}}"
    username: "{{svn_user}}"
    password: "{{svn_pass}}"
    dest: "{{item.path}}"
    export: yes
    force: yes
  with_items: "{{zones.files}}"
  when: "(item.path.split('_')[2]|int) in zone_num and opt == 'con'"
  register: svn_ret