---
- name: find game directory
  find:
    paths: "{{game_directory}}"
    file_type: directory
    use_regex: yes
    patterns: 
      - "{{zone_repx}}"
  register: zones
- name: update bin
  copy: 
    src: "{{bin_file}}"
    dest: "{{item.path}}" 
    mode: 755
  with_items: "{{zones.files}}"
- name: update config
  subversion: 
    repo: "{{svn_url}}"
    username: "{{svn_user}}"
    password: "{{svn_pass}}"
    dest: "{{item.path}}"
    export: yes
    force: yes
  with_items: "{{zones.files}}"
