---

- name: "create game directory" 
  file:
    path: "{{game_directory}}{{zone_name}}_{{item}}"
    state: directory
  with_items: "{{zone_num}}"

- name: "get bin file"
  copy:
    src: "{{bin_file}}"
    dest: "{{game_directory}}{{zone_name}}_{{item}}"
    mode: '0755'
  with_items: "{{zone_num}}"

- name: get config file
  subversion:
    repo: "{{svn_url}}"
    username: "{{svn_user}}"
    password: "{{svn_pass}}"
    dest: "{{game_directory}}{{zone_name}}_{{item}}"
    export: yes
    in_place: yes
    force: yes
  with_items: "{{zone_num}}"